### ISSUE TITLE
error while loading shared library

### ISSUE THREAD

**Issue by wxdwfc** [yaledb/calvin#4]
Hi, i follow the instructions from the README and when i've successfully built the calvin, i use  bin/deployment/cluster -c deploy-run.conf -p src/deployment/portfile -d bin/deployment/db m 0 ;but got a error: scp: db3/deploy-run.conf: No such file or directory
00: bin/deployment/db: error while loading shared libraries: libprotobuf.so.9: cannot open shared object file: No such file or directory

I'm definatelly sure that i have set the LD_LIBRARY_PATH on my machine.In my deploy-run.conf,i write only one line which is that  node0=0:1:8:10.0.0.102:54580.

Can anyone give some tips about this? 
Thanks a lot!

**Comment by yaledb** [comment]
Hi wxdwfc,

Thanks for your interest. 
1. First, you should change your deploy-run.conf line to "node0=0:0:8:10.0.0.102:54580", because the format is "# Node<id>=<replica>:<partition>:<cores>:<host>:<port>". Please note that it is 0:0, not 0:1, since you only have one partition, and you want to run it on that partition, not the second partition.
2.  If you did the first step, I think you will not get the "No such file or directory" error. 
3. For "error while loading shared libraries: libprotobuf.so.9: cannot open shared object file: No such file or directory", I think probably because of the LD_LIBRARY_PATH setting of protobuf, please make sure you install protobuf and include the protobuf library in LD_LIBRARY_PATH,  in my machine, the LD_LIBRARY_PATH is "/home/accts/kr358/db3/ext/zeromq/src/.libs:/home/accts/kr358/db3/ext/protobuf/src/.libs:/home/accts/kr358/db3/ext/googletest/lib/.libs:/home/accts/kr358/db3/ext/zookeeper/.libs"

4. Try run it now, also, if you just run it on one machine, you can use the following command to run it:
bin/deployment/db 0 m 0

Hope this helps.

**Comment by wxdwfc** [comment]
Oh,I think i forget to set the LD_LIBRARY_PATH in ~/.ssh/environment.And after that the problem is fixed.
Thanks again!

**Comment by yaledb** [comment]
I am glad you fixed it, also please note the step 1, use node0=0:0:8:10.0.0.102:54580 for your deploy-run.conf.(Not node0=0:1:8:10.0.0.102:54580).
